version: '3'

services:

   mariadb:
      image: mariadb:${MARIADB_VERSION:-latest}
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - ./mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
      container_name: "${MARIADB_NAME}"
